include:
- ./func/*
kind: ArchiveUploadSpec
name: func-lXbG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onboarding-ouroinvest-fn-b3ae9ea3-b810-4f6c-8fc3-7352cd5b84ac
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: onboarding-ouroinvest-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-lXbG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-10-06T19:02:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onboarding-ouroinvest-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: onboarding-ouroinvest-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.onboarding_ouroinvest
    packageref:
      name: onboarding-ouroinvest-fn-b3ae9ea3-b810-4f6c-8fc3-7352cd5b84ac
      namespace: default
  requestsPerPod: 10000
  resources: {}
