apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: onboarding-ouroinvest-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onboarding-ouroinvest-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ouroinvest/onboarding-ouroinvest
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /ouroinvest/onboarding-ouroinvest
